server:
  port: 8080

spring:
  profiles:
    active: test
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${nobi.datasource.driver-class-name}
      url: jdbc:mysql://${nobi.datasource.host}:${nobi.datasource.port}/${nobi.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${nobi.datasource.username}
      password: ${nobi.datasource.password}
  redis:
    host: ${nobi.redis.host}
    port: ${nobi.redis.port}
    database: ${nobi.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xipian.nobi.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      xipian:
        nobi:
          mapper: debug
          service: info
          controller: info

nobi:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: xipian
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: nobi
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    endpoint: ${nobi.alioss.endpoint}
    access-key-id: ${nobi.alioss.access-key-id}
    access-key-secret: ${nobi.alioss.access-key-secret}
    bucket-name: ${nobi.alioss.bucket-name}
  wechat:
    appid: ${nobi.wechat.appid}
    secret: ${nobi.wechat.secret}
    mchid: ${nobi.wechat.mchid}
    mchSerialNo: ${nobi.wechat.mchSerialNo}
    privateKeyFilePath: ${nobi.wechat.privateKeyFilePath}
    apiV3Key: ${nobi.wechat.apiV3Key}
    weChatPayCertFilePath: ${nobi.wechat.weChatPayCertFilePath}
    notifyUrl: ${nobi.wechat.notifyUrl}
    refundNotifyUrl: ${nobi.wechat.refundNotifyUrl}
